name: validate-terraform-conf
defaults:
  run:
    shell: bash
    working-directory: ./windows-virtual-desktop/current/terraform
    
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  integration-and-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize environment
        run: terraform init

      - name: Format configuration
        run: terraform fmt

      - name: Create execution plan
        run: terraform plan \
              -var "aad_tenant_id=${{ secrets.AAD_TENANT_ID }}"\
              -var "subscription_id=${{ secrets.SUBSCRIPTION_ID }}"\
              -var 'terraform_sp={"client_id":"${{ secrets.SP_DEV_TERRAFORM_ID }}","client_secret":"${{ secrets.SP_DEV_TERRAFORM_SECRET }}"}'\
              -var 'wvd_domain_join_account={"username":"${{ secrets.SP_JOINDOMAIN_ID }}","password":"${{ secrets.SP_JOINDOMAIN_SECRET }}"}'\
              -var 'wvd_local_admin_account={"username":"${{ secrets.SP_LOCALADMIN_ID }}","password":"${{ secrets.SP_LOCALADMIN_SECRET }}"}'          
          
      - name: Apply execution plan
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform plan \
              -var "aad_tenant_id=${{ secrets.AAD_TENANT_ID }}" \
              -var "subscription_id=${{ secrets.SUBSCRIPTION_ID }}" \
              -var 'terraform_sp={"client_id":"${{ secrets.SP_DEV_TERRAFORM_ID }}","client_secret":"${{ secrets.SP_DEV_TERRAFORM_SECRET }}"}' \
              -var 'wvd_domain_join_account={"username":"${{ secrets.SP_JOINDOMAIN_ID }}","password":"${{ secrets.SP_JOINDOMAIN_SECRET }}"}' \
              -var 'wvd_local_admin_account={"username":"${{ secrets.SP_LOCALADMIN_ID }}","password":"${{ secrets.SP_LOCALADMIN_SECRET }}"}'          
