name: validate-terraform-conf
defaults:
  run:
    shell: bash
    working-directory: ./windows-virtual-desktop/current/terraform
    
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize
        run: terraform init 
              -backend-config="tenant_id=${{ secrets.AAD_TENANT_ID }}"
              -backend-config="subscription_id=${{ secrets.SUBSCRIPTION_ID }}"
              -backend-config="client_id=${{ secrets.SP_DEV_TERRAFORM_ID }}"
              -backend-config="client_secret=${{ secrets.SP_DEV_TERRAFORM_SECRET }}"

      - name: Format
        run: terraform fmt

      - name: Plan
        run: terraform plan 
              -var "aad_tenant_id=${{ secrets.AAD_TENANT_ID }}"
              -var "subscription_id=${{ secrets.SUBSCRIPTION_ID }}"
              -var 'terraform_sp={"client_id":"${{ secrets.SP_DEV_TERRAFORM_ID }}","client_secret":"${{ secrets.SP_DEV_TERRAFORM_SECRET }}"}'
              -var 'wvd_domain_join_account={"username":"${{ secrets.SP_JOINDOMAIN_ID }}","password":"${{ secrets.SP_JOINDOMAIN_SECRET }}"}'
              -var 'wvd_local_admin_account={"username":"${{ secrets.SP_LOCALADMIN_ID }}","password":"${{ secrets.SP_LOCALADMIN_SECRET }}"}'          
          
      - name: Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve
              -var "aad_tenant_id=${{ secrets.AAD_TENANT_ID }}" 
              -var "subscription_id=${{ secrets.SUBSCRIPTION_ID }}" 
              -var 'terraform_sp={"client_id":"${{ secrets.SP_DEV_TERRAFORM_ID }}","client_secret":"${{ secrets.SP_DEV_TERRAFORM_SECRET }}"}' 
              -var 'wvd_domain_join_account={"username":"${{ secrets.SP_JOINDOMAIN_ID }}","password":"${{ secrets.SP_JOINDOMAIN_SECRET }}"}' 
              -var 'wvd_local_admin_account={"username":"${{ secrets.SP_LOCALADMIN_ID }}","password":"${{ secrets.SP_LOCALADMIN_SECRET }}"}'          
      
      - name: Destroy
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform destroy
